language: python
python:
  - "3.4"
git:
    submodules: false # Handle git submodules yourself
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules # Use sed to replace the ssh url with public https url
notifications:
  email: false
install:
  - sudo apt-get -y update
  - sudo apt-get -y install libxml2 libxslt1.1 libzip2 python-virtualenv pyflakes sqlite build-essential zlibc curl file git ruby nodejs npm phantomjs leiningen maven tomcat7 openjdk-7-jdk supervisor nginx
script:
  make
